# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 00:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkyDevice',
            fields=[
                ('DeviceID', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('LatestFWVersion1', models.CharField(default='0.0.0', max_length=14)),
                ('LatestFWVersion2', models.CharField(default='0.0.0', max_length=14)),
                ('LAT', models.FloatField(default=0)),
                ('LON', models.FloatField(default=0)),
                ('ALT', models.FloatField(default=0)),
                ('UTC', models.SmallIntegerField(default=0)),
                ('DST', models.SmallIntegerField(default=0)),
                ('Searchable', models.BooleanField(default=True)),
                ('RegisterTime', models.PositiveIntegerField(default=0)),
                ('CityName', models.CharField(max_length=200)),
                ('StreetName', models.CharField(max_length=200)),
                ('FullAddress', models.TextField()),
                ('DeviceName', models.CharField(max_length=100)),
                ('RainNotification', models.BooleanField(default=False)),
                ('BatteryNotification', models.BooleanField(default=False)),
                ('C_or_F', models.BooleanField(default=True)),
                ('Tag', models.CharField(default='', max_length=500)),
                ('Description', models.TextField(default='')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
