"""
Django settings for WidgetIDGenerator project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o)fdoj7zb+n=h&^dq^0u=z$d+ywc6u635o*sn)fbsirjry$)@j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['widget-env.ymdwywpdcr.us-west-1.elasticbeanstalk.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget',
    'corsheaders',
    'appi',
    'app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'WidgetIDGenerator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WidgetIDGenerator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

if os.getenv('SERVER_SOFTWARE', '').startswith('Google App Engine'):
    DATABASES = {
         'default':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'bloomsky',
            'USER': 'Yang',
            'PASSWORD': '12345678',
            'HOST': 'bloomsky.cb2tvmnyo0zz.us-west-1.rds.amazonaws.com',
            'PORT': '3306',
         },
         'mysql': {
            'ENGINE': 'django.db.backends.mysql',
            'HOST': '/cloudsql/bloomsky-widget:bsky-widgetdb',
            'NAME': 'widgetDB',
            'USER': 'root',
            'PASSWORD': 'Bl00mSt@rm',
            # 'USER': 'yang',
            # 'PASSWORD': '123456',
         }

     }
else:
     DATABASES = {
         'mysql':{
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'bloomsky',
            'USER': 'Yang',
            'PASSWORD': '12345678',
            'HOST': 'bloomsky.cb2tvmnyo0zz.us-west-1.rds.amazonaws.com',
            'PORT': '3306',
         },
         'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'widgetDB',
            'HOST': '173.194.108.113',
            # 'USER': 'root',
            # 'PASSWORD': 'Bl00mSt@rm',
            'USER': 'yang',
            'PASSWORD': '123456',
         }

     }



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'US/Pacific'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = 'static'
STATIC_URL = '/static/'

CORS_ORIGIN_ALLOW_ALL = True
